### PR TITLE
Moving gptp folder outside OpenAVnu

### PR DESCRIPTION
**Pull request by avinash-palleti**
Updated CmakeLists.txt file and added travis-ci files.

### CODE REVIEW

**Comment by avinash-palleti** [comment]
Will have to wait till gptp repo shows up in Travis-CI

**Comment by pinealservo** [comment]
The repo was not active yet in Travis-CI. I activated it, but it did not pick up the pull request and there doesn't seem to be a way to tell it to build a pending PR. We could manually trigger a build, but it wouldn't do anything since this there's no travis.yml before this PR.

**Comment by andrew-elder** [comment]
@avinash-palleti - I don't see the rest of the gptp files in this pull request?

**Comment by avinash-palleti** [comment]
@andrew-elder If there are no further comments on this, can you please merge this.

**Pull request merged**
