### PR TITLE
SCA fixes (part I)

### PR DESCRIPTION
**Pull request by PawelModrzejewski**
This is a first batch of fixes for issues found by static code analysis.

### CODE REVIEW

**Comment by PawelModrzejewski** [comment]
[gptp_001.txt](https://github.com/Avnu/gptp/files/5620990/gptp_001.txt)
[gptp_006.txt](https://github.com/Avnu/gptp/files/5620991/gptp_006.txt)
[gptp_012.txt](https://github.com/Avnu/gptp/files/5620992/gptp_012.txt)
[gptp_021.txt](https://github.com/Avnu/gptp/files/5620993/gptp_021.txt)
[gptp_022.txt](https://github.com/Avnu/gptp/files/5620994/gptp_022.txt)
[gptp_023.txt](https://github.com/Avnu/gptp/files/5620995/gptp_023.txt)
[gptp_024.txt](https://github.com/Avnu/gptp/files/5620996/gptp_024.txt)
[gptp_025.txt](https://github.com/Avnu/gptp/files/5620997/gptp_025.txt)

Analysis details for each case attached.

**Comment by PawelModrzejewski** [comment]
Hi Guys, any comments here?

**Comment by SiMet** [comment]
From my perspective it looks good. However, I'm not a maintainer

**Comment by PawelModrzejewski** [comment]
@SiMet thanks!

Any other comments, from anyone ?

**Review by avinash-palleti — APPROVED** [review]

**Pull request merged**
